export const CATEGORIES = ['全部', '洗臉皂', '身體皂', '洗髮皂', '禮盒組', '季節限定']

export const PRODUCTS = [
  // ── 洗臉皂 ─────────────────────────────────────────────────
  {
    id: 'p01',
    name: '薰衣草蜂蜜洗臉皂',
    subtitle: 'Lavender & Honey',
    category: '洗臉皂',
    price: 380,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=800&q=80',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
    ],
    weight: '100g',
    description: '採用普羅旺斯薰衣草精油與天然蜂蜜製成，溫和滋潤，適合敏感肌與乾性肌。豐富的保濕因子讓洗後肌膚水嫩不緊繃。',
    ingredients: ['橄欖油', '椰子油', '薰衣草精油', '天然蜂蜜', '乳油木果脂'],
    features: ['溫和保濕', '敏感肌適用', '天然香氛'],
    rating: 4.9,
    reviewCount: 128,
    stock: 42,
    badge: '熱銷',
    scent: '薰衣草',
  },
  {
    id: 'p02',
    name: '玫瑰天竺葵洗臉皂',
    subtitle: 'Rose Geranium',
    category: '洗臉皂',
    price: 420,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80',
    ],
    weight: '100g',
    description: '玫瑰天竺葵精油擁有平衡油脂、緊緻毛孔的功效，搭配玫瑰果油豐富的維生素E，賦予肌膚光澤與彈性。',
    ingredients: ['玫瑰果油', '甜杏仁油', '天竺葵精油', '玫瑰花水', '高嶺土'],
    features: ['毛孔細緻', '控油平衡', '抗氧化'],
    rating: 4.8,
    reviewCount: 96,
    stock: 28,
    badge: null,
    scent: '玫瑰花香',
  },
  {
    id: 'p03',
    name: '綠茶竹炭洗臉皂',
    subtitle: 'Green Tea & Charcoal',
    category: '洗臉皂',
    price: 360,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=80',
    ],
    weight: '100g',
    description: '竹炭強力吸附毛孔油脂與汙垢，綠茶萃取物提供抗氧化保護，適合油性肌與痘痘肌使用，清爽潔淨感持久。',
    ingredients: ['椰子油', '棕櫚油', '竹炭粉', '綠茶萃取', '茶樹精油'],
    features: ['深層清潔', '控油平衡', '抗菌淨膚'],
    rating: 4.7,
    reviewCount: 74,
    stock: 15,
    badge: '低庫存',
    scent: '清新草木',
  },
  // ── 身體皂 ─────────────────────────────────────────────────
  {
    id: 'p04',
    name: '燕麥牛奶身體皂',
    subtitle: 'Oat & Milk',
    category: '身體皂',
    price: 320,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=800&q=80',
    ],
    weight: '120g',
    description: '膠體燕麥與山羊奶入皂，天然細膩的泡沫呵護全身肌膚，洗後柔滑細嫩。適合全家大小使用，包含嬰幼兒。',
    ingredients: ['山羊奶', '燕麥粉', '甜杏仁油', '橄欖油', '乳油木果脂'],
    features: ['溫和潔淨', '全家適用', '滋潤柔嫩'],
    rating: 4.9,
    reviewCount: 203,
    stock: 67,
    badge: '暢銷',
    scent: '淡淡奶香',
  },
  {
    id: 'p05',
    name: '雪松咖啡去角質皂',
    subtitle: 'Cedar & Coffee Scrub',
    category: '身體皂',
    price: 350,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&q=80',
    ],
    weight: '130g',
    description: '咖啡渣天然去角質，促進血液循環；雪松精油舒緩身心。沐浴後肌膚光滑細緻，讓您在家享受SPA般的體驗。',
    ingredients: ['椰子油', '咖啡渣', '雪松精油', '可可脂', '荷荷芭油'],
    features: ['去角質', '促進循環', '舒緩療癒'],
    rating: 4.8,
    reviewCount: 89,
    stock: 32,
    badge: null,
    scent: '雪松咖啡',
  },
  {
    id: 'p06',
    name: '檸檬薄荷提神皂',
    subtitle: 'Lemon & Mint',
    category: '身體皂',
    price: 310,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    ],
    weight: '120g',
    description: '清新檸檬與薄荷的組合，早晨使用能迅速喚醒精神。薄荷帶來涼爽感受，適合夏日沐浴或運動後使用。',
    ingredients: ['椰子油', '棕櫚油', '檸檬精油', '薄荷精油', '檸檬乾皮'],
    features: ['提神醒腦', '清爽涼感', '天然防臭'],
    rating: 4.7,
    reviewCount: 56,
    stock: 44,
    badge: null,
    scent: '清新柑橘薄荷',
  },
  // ── 洗髮皂 ─────────────────────────────────────────────────
  {
    id: 'p07',
    name: '迷迭香控油洗髮皂',
    subtitle: 'Rosemary Shampoo Bar',
    category: '洗髮皂',
    price: 450,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&q=80',
    ],
    weight: '80g',
    description: '迷迭香精油促進頭皮血液循環，有效控制頭皮出油。環保固體洗髮皂，相當於400ml洗髮精，減少塑料使用。',
    ingredients: ['蓖麻油', '椰子油', '迷迭香精油', '荷荷芭油', '泛醇'],
    features: ['環保減塑', '控油清爽', '促進生長'],
    rating: 4.6,
    reviewCount: 147,
    stock: 58,
    badge: '環保',
    scent: '草本迷迭香',
  },
  {
    id: 'p08',
    name: '摩洛哥堅果深層護髮皂',
    subtitle: 'Argan Nourishing Bar',
    category: '洗髮皂',
    price: 520,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&q=80',
    ],
    weight: '80g',
    description: '黃金摩洛哥堅果油深層滋養受損髮絲，豐富的維生素E修復毛鱗片，讓頭髮恢復光澤與柔順。乾性及受損髮適用。',
    ingredients: ['摩洛哥堅果油', '椰子油', '乳木果油', '玫瑰木精油', '蛋白質'],
    features: ['修復受損', '強韌髮絲', '增添光澤'],
    rating: 4.8,
    reviewCount: 92,
    stock: 21,
    badge: '新品',
    scent: '淡雅木質',
  },
  // ── 禮盒組 ─────────────────────────────────────────────────
  {
    id: 'p09',
    name: '純粹日常禮盒 — 入門組',
    subtitle: 'Pure Daily Gift Set',
    category: '禮盒組',
    price: 980,
    originalPrice: 1140,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&q=80',
    ],
    weight: '3入',
    description: '精選三款暢銷洗臉皂，以環保牛皮紙盒精心包裝。附有手寫賀卡，適合生日、節日贈禮。內含：薰衣草蜂蜜皂、玫瑰天竺葵皂、燕麥牛奶皂各一。',
    ingredients: [],
    features: ['精美包裝', '附手寫賀卡', '環保材質'],
    rating: 4.9,
    reviewCount: 312,
    stock: 18,
    badge: '送禮首選',
    scent: '多重香氛',
  },
  {
    id: 'p10',
    name: '奢寵全身禮盒 — 豪華組',
    subtitle: 'Luxury Full Body Set',
    category: '禮盒組',
    price: 1680,
    originalPrice: 2060,
    image: 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=800&q=80',
    ],
    weight: '6入',
    description: '六款手工皂的豪華組合，涵蓋洗臉、身體、洗髮全方位護理。附贈手工皂盒與麻繩皂袋，以精緻木盒呈現，適合重要場合送禮。',
    ingredients: [],
    features: ['木盒精裝', '全方位護理', '附皂架'],
    rating: 5.0,
    reviewCount: 87,
    stock: 8,
    badge: '限量',
    scent: '多重香氛',
  },
  // ── 季節限定 ───────────────────────────────────────────────
  {
    id: 'p11',
    name: '春日茉莉限定皂',
    subtitle: 'Spring Jasmine Limited',
    category: '季節限定',
    price: 430,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1591621688576-cbe7de91c059?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1591621688576-cbe7de91c059?w=800&q=80',
    ],
    weight: '100g',
    description: '每年春季限量製作，以新鮮茉莉花浸泡橄欖油，帶來馥郁的花香氣息。手工包埋真實茉莉花瓣，每一塊都是獨一無二的藝術品。',
    ingredients: ['茉莉浸泡橄欖油', '椰子油', '茉莉精油', '茉莉花瓣', '乳木果油'],
    features: ['季節限量', '真實花瓣', '藝術手作'],
    rating: 4.9,
    reviewCount: 64,
    stock: 12,
    badge: '季節限定',
    scent: '茉莉花香',
  },
  {
    id: 'p12',
    name: '冬季暖薑肉桂皂',
    subtitle: 'Winter Ginger & Cinnamon',
    category: '季節限定',
    price: 410,
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=800&q=80',
    ],
    weight: '110g',
    description: '暖薑與肉桂的冬季香氛，促進全身血液循環，驅走寒意。適合冬日沐浴，沐浴後肌膚暖意融融，身心放鬆。',
    ingredients: ['棕櫚油', '椰子油', '薑精油', '肉桂精油', '薑粉'],
    features: ['溫暖促循環', '驅寒暖身', '冬季限定'],
    rating: 4.8,
    reviewCount: 43,
    stock: 20,
    badge: '季節限定',
    scent: '暖薑肉桂',
  },
]

export const getFeatured = () => PRODUCTS.filter((p) => p.badge === '熱銷' || p.badge === '暢銷' || p.badge === '送禮首選')
export const getByCategory = (cat) => cat === '全部' ? PRODUCTS : PRODUCTS.filter((p) => p.category === cat)
export const getById = (id) => PRODUCTS.find((p) => p.id === id)
export const getRelated = (id, limit = 4) => PRODUCTS.filter((p) => p.id !== id).slice(0, limit)

export const SHIPPING_OPTIONS = [
  {
    id: 'home_std',
    label: '標準宅配',
    desc: '黑貓宅急便 / 新竹物流',
    days: '2–4 個工作天',
    fee: 100,
    freeOver: 1200,
    icon: '🏠',
  },
  {
    id: 'cvs_711',
    label: '7-11 超商取貨',
    desc: '全台 7-11 門市取貨',
    days: '2–3 個工作天',
    fee: 60,
    freeOver: 800,
    icon: '🏪',
  },
  {
    id: 'cvs_family',
    label: '全家 FamilyMart 取貨',
    desc: '全台全家門市取貨',
    days: '2–3 個工作天',
    fee: 60,
    freeOver: 800,
    icon: '🏪',
  },
  {
    id: 'international',
    label: '海外運送',
    desc: '支援全球主要國家',
    days: '7–14 個工作天',
    fee: 580,
    freeOver: 5000,
    icon: '✈️',
  },
]
